In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("beer_cleaned.csv")

df.head()

,abv,ibu,beer_id,beer_name,style,style_group,ounces,brewery_id
0,0.061,60.0,1979,Bitter Bitch,American Pale Ale (APA),American Pale Ale (APA),12.0,177
1,0.099,92.0,1036,Lower De Boom,American Barleywine,other,8.4,368
2,0.079,45.0,1024,Fireside Chat,Winter Warmer,other,12.0,368
3,0.044,42.0,876,Bitter American,American Pale Ale (APA),American Pale Ale (APA),12.0,368
4,0.049,17.0,802,Hell or High Watermelon Wheat (2009),Fruit / Vegetable Beer,Fruit / Vegetable Beer,12.0,368

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

(1326, 8)
<class 'pandas.DataFrame'>
RangeIndex: 1326 entries, 0 to 1325
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   abv          1326 non-null   float64
 1   ibu          1326 non-null   float64
 2   beer_id      1326 non-null   int64
 3   beer_name    1326 non-null   str
 4   style        1326 non-null   str
 5   style_group  1326 non-null   str
 6   ounces       1326 non-null   float64
 7   brewery_id   1326 non-null   int64
dtypes: float64(3), int64(2), str(3)
memory usage: 145.3 KB
None
               abv          ibu      beer_id       ounces   brewery_id
count  1326.000000  1326.000000  1326.000000  1326.000000  1326.000000
mean      0.060181    42.993213  1426.049774    13.490573   224.383107
std       0.013618    26.003352   751.164068     2.259052   150.841367
min       0.027000     4.000000     4.000000     8.400000     0.000000
25%       0.050000    22.000000   790.250000    12.000000    98.000000
50%       0.057000    35.000000  1459.500000    12.000000   198.500000
75%       0.068000    64.000000  2067.750000    16.000000   350.000000
max       0.125000   138.000000  2692.000000    32.000000   546.000000

In [4]:
df = df.dropna()  # simple approach; you can improve later

In [5]:
TARGET = "target_column_name"  # <-- CHANGE THIS

In [7]:
text_cols = df.select_dtypes(include=["object", "string"]).columns

for col in text_cols:
    if df[col].dtype.name in ["object", "string"]:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))
        label_encoders[col] = le

In [10]:
df.columns = df.columns.str.strip()

In [13]:
df.head()

     abv   ibu  beer_id  beer_name  style  style_group  ounces  brewery_id
0  0.061  60.0     1979        145     15            5    12.0         177
1  0.099  92.0     1036        744      5           10     8.4         368
2  0.079  45.0     1024        420     88           10    12.0         368
3  0.044  42.0      876        143     15            5    12.0         368
4  0.049  17.0      802        561     55            8    12.0         368

In [19]:
print(df.columns)
df.head()

Index(['abv', 'ibu', 'beer_id', 'beer_name', 'style', 'style_group', 'ounces',
       'brewery_id'],
      dtype='str')

,abv,ibu,beer_id,beer_name,style,style_group,ounces,brewery_id
0,0.061,60.0,1979,Bitter Bitch,American Pale Ale (APA),American Pale Ale (APA),12.0,177
1,0.099,92.0,1036,Lower De Boom,American Barleywine,other,8.4,368
2,0.079,45.0,1024,Fireside Chat,Winter Warmer,other,12.0,368
3,0.044,42.0,876,Bitter American,American Pale Ale (APA),American Pale Ale (APA),12.0,368
4,0.049,17.0,802,Hell or High Watermelon Wheat (2009),Fruit / Vegetable Beer,Fruit / Vegetable Beer,12.0,368