In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load your dataset
df = pd.read_csv("console_data.csv")

# Preview
df.head()

   console_id console
0           0  Series
1           1     PS3
2           2     PS4
3           3     PS2
4           4    X360

In [4]:
for col in df.select_dtypes(include=['string']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [7]:
df.head()
df.columns

Index(['console_id', 'console'], dtype='str')

In [10]:
print(df.columns)

Index(['console_id', 'console'], dtype='str')

In [14]:
df.head()
df.columns

Index(['console_id', 'console'], dtype='str')

In [17]:
df.head()

   console_id  console
0           0       32
1           1       24
2           2       25
3           3       23
4           4       38

In [19]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

rf = RandomForestClassifier(random_state=42)
rt = ExtraTreesClassifier(random_state=42)

In [23]:
df.head()
df.columns

Index(['console_id', 'console'], dtype='str')