In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.read_csv("grosses.csv")

df.head()

  week_ending  week_number  ...  performances previews
0  1985-06-09            1  ...             8        0
1  1985-06-09            1  ...             8        0
2  1985-06-09            1  ...             8        0
3  1985-06-09            1  ...             8        0
4  1985-06-09            1  ...             8        0

[5 rows x 14 columns]

In [3]:
# Drop missing values (simple approach)
df = df.dropna()

# If there are categorical columns, convert them
df = pd.get_dummies(df, drop_first=True)

df.head()

      week_number  ...  theatre_Winter Garden Theatre
6861           42  ...                          False
6884           43  ...                          False
6908           44  ...                          False
6934           45  ...                          False
6963           46  ...                          False

[5 rows x 2126 columns]

In [5]:
print(df.columns.tolist())

['week_number', 'weekly_gross_overall', 'weekly_gross', 'potential_gross', 'avg_ticket_price', 'top_ticket_price', 'seats_sold', 'seats_in_theatre', 'pct_capacity', 'performances', 'previews', 'week_ending_1992-03-29', 'week_ending_1992-04-05', 'week_ending_1992-04-12', 'week_ending_1992-04-19', 'week_ending_1992-04-26', 'week_ending_1992-05-03', 'week_ending_1992-05-10', 'week_ending_1992-05-17', 'week_ending_1992-05-24', 'week_ending_1992-05-31', 'week_ending_1992-06-07', 'week_ending_1992-06-14', 'week_ending_1992-06-21', 'week_ending_1992-06-28', 'week_ending_1992-07-05', 'week_ending_1992-07-12', 'week_ending_1992-07-19', 'week_ending_1992-07-26', 'week_ending_1992-08-02', 'week_ending_1992-08-09', 'week_ending_1994-03-20', 'week_ending_1994-03-27', 'week_ending_1994-04-03', 'week_ending_1995-04-16', 'week_ending_1995-04-23', 'week_ending_1995-04-30', 'week_ending_1995-05-07', 'week_ending_1995-05-14', 'week_ending_1995-05-21', 'week_ending_1995-05-28', 'week_ending_1995-06-04', 'week_ending_1995-06-11', 'week_ending_1995-06-18', 'week_ending_1995-06-25', 'week_ending_1995-07-02', 'week_ending_1995-07-09', 'week_ending_1995-07-16', 'week_ending_1995-07-23', 'week_ending_1995-07-30', 'week_ending_1995-08-06', 'week_ending_1995-08-13', 'week_ending_1995-08-20', 'week_ending_1995-08-27', 'week_ending_1995-09-03', 'week_ending_1995-09-10', 'week_ending_1995-09-17', 'week_ending_1995-09-24', 'week_ending_1995-10-01', 'week_ending_1995-10-08', 'week_ending_1995-10-15', 'week_ending_1995-10-22', 'week_ending_1995-10-29', 'week_ending_1995-11-05', 'week_ending_1995-11-12', 'week_ending_1995-11-19', 'week_ending_1995-11-26', 'week_ending_1995-12-03', 'week_ending_1995-12-10', 'week_ending_1995-12-17', 'week_ending_1995-12-24', 'week_ending_1995-12-31', 'week_ending_1996-02-04', 'week_ending_1996-02-11', 'week_ending_1996-02-18', 'week_ending_1996-03-24', 'week_ending_1996-03-31', 'week_ending_1996-04-07', 'week_ending_1996-04-14', 'week_ending_1996-04-21', 'week_ending_1996-04-28', 'week_ending_1996-05-05', 'week_ending_1996-05-12', 'week_ending_1996-05-19', 'week_ending_1996-05-26', 'week_ending_1997-03-16', 'week_ending_1997-03-23', 'week_ending_1997-03-30', 'week_ending_1997-04-06', 'week_ending_1997-04-13', 'week_ending_1997-04-20', 'week_ending_1997-04-27', 'week_ending_1997-05-04', 'week_ending_1997-05-11', 'week_ending_1997-05-18', 'week_ending_1997-05-25', 'week_ending_1997-06-01', 'week_ending_1997-06-08', 'week_ending_1997-06-15', 'week_ending_1997-06-22', 'week_ending_1997-06-29', 'week_ending_1997-07-06', 'week_ending_1997-07-13', 'week_ending_1997-07-20', 'week_ending_1997-07-27', 'week_ending_1997-08-03', 'week_ending_1997-08-10', 'week_ending_1997-08-17', 'week_ending_1997-08-24', 'week_ending_1997-08-31', 'week_ending_1997-09-07', 'week_ending_1997-09-14', 'week_ending_1997-09-21', 'week_ending_1997-09-28', 'week_ending_1997-10-05', 'week_ending_1997-10-12', 'week_ending_1997-10-19', 'week_ending_1997-10-26', 'week_ending_1997-11-02', 'week_ending_1997-11-09', 'week_ending_1997-11-16', 'week_ending_1997-11-23', 'week_ending_1997-11-30', 'week_ending_1997-12-07', 'week_ending_1997-12-14', 'week_ending_1997-12-21', 'week_ending_1997-12-28', 'week_ending_1998-01-04', 'week_ending_1998-01-11', 'week_ending_1998-01-18', 'week_ending_1998-01-25', 'week_ending_1998-02-01', 'week_ending_1998-02-08', 'week_ending_1998-02-15', 'week_ending_1998-02-22', 'week_ending_1998-03-01', 'week_ending_1998-03-08', 'week_ending_1998-03-15', 'week_ending_1998-03-22', 'week_ending_1998-03-29', 'week_ending_1998-04-05', 'week_ending_1998-04-12', 'week_ending_1998-04-19', 'week_ending_1998-04-26', 'week_ending_1998-05-03', 'week_ending_1998-05-10', 'week_ending_1998-05-17', 'week_ending_1998-05-24', 'week_ending_1998-05-31', 'week_ending_1998-06-07', 'week_ending_1998-06-14', 'week_ending_1998-06-21', 'week_ending_1998-06-28', 'week_ending_1998-07-05', 'week_ending_1998-07-12', 'week_ending_1998-07-19', 'week_ending_1998-07-26', 'week_ending_1998-08-02', 'week_ending_1998-08-09', 'week_ending_1998-08-16', 'week_ending_1998-08-23', 'week_ending_1998-08-30', 'week_ending_1998-09-06', 'week_ending_1998-09-13', 'week_ending_1998-09-20', 'week_ending_1998-09-27', 'week_ending_1998-10-04', 'week_ending_1998-10-11', 'week_ending_1998-10-18', 'week_ending_1998-10-25', 'week_ending_1998-11-01', 'week_ending_1998-11-08', 'week_ending_1998-11-15', 'week_ending_1998-11-22', 'week_ending_1998-11-29', 'week_ending_1998-12-06', 'week_ending_1998-12-13', 'week_ending_1998-12-20', 'week_ending_1998-12-27', 'week_ending_1999-01-03', 'week_ending_1999-01-10', 'week_ending_1999-01-17', 'week_ending_1999-01-24', 'week_ending_1999-01-31', 'week_ending_1999-02-07', 'week_ending_1999-02-14', 'week_ending_1999-02-21', 'week_ending_1999-02-28', 'week_ending_1999-03-07', 'week_ending_1999-03-14', 'week_ending_1999-03-21', 'week_ending_1999-03-28', 'week_ending_1999-04-04', 'week_ending_1999-04-11', 'week_ending_1999-04-18', 'week_ending_1999-04-25', 'week_ending_1999-05-02', 'week_ending_1999-05-09', 'week_ending_1999-05-16', 'week_ending_1999-05-23', 'week_ending_1999-05-30', 'week_ending_1999-06-06', 'week_ending_1999-06-13', 'week_ending_1999-06-20', 'week_ending_1999-06-27', 'week_ending_1999-07-04', 'week_ending_1999-07-11', 'week_ending_1999-07-18', 'week_ending_1999-07-25', 'week_ending_1999-08-01', 'week_ending_1999-08-08', 'week_ending_1999-08-15', 'week_ending_1999-08-22', 'week_ending_1999-08-29', 'week_ending_1999-09-05', 'week_ending_1999-09-12', 'week_ending_1999-09-19', 'week_ending_1999-09-26', 'week_ending_1999-10-03', 'week_ending_1999-10-10', 'week_ending_1999-10-17', 'week_ending_1999-10-24', 'week_ending_1999-10-31', 'week_ending_1999-11-07', 'week_ending_1999-11-14', 'week_ending_1999-11-21', 'week_ending_1999-11-28', 'week_ending_1999-12-05', 'week_ending_1999-12-12', 'week_ending_1999-12-19', 'week_ending_1999-12-26', 'week_ending_2000-01-02', 'week_ending_2000-01-09', 'week_ending_2000-01-16', 'week_ending_2000-01-23', 'week_ending_2000-01-30', 'week_ending_2000-02-06', 'week_ending_2000-02-13', 'week_ending_2000-02-20', 'week_ending_2000-02-27', 'week_ending_2000-03-05', 'week_ending_2000-03-12', 'week_ending_2000-03-19', 'week_ending_2000-03-26', 'week_ending_2000-04-02', 'week_ending_2000-04-09', 'week_ending_2000-04-16', 'week_ending_2000-04-23', 'week_ending_2000-04-30', 'week_ending_2000-05-07', 'week_ending_2000-05-14', 'week_ending_2000-05-21', 'week_ending_2000-05-28', 'week_ending_2000-06-04', 'week_ending_2000-06-11', 'week_ending_2000-06-18', 'week_ending_2000-06-25', 'week_ending_2000-07-02', 'week_ending_2000-07-09', 'week_ending_2000-07-16', 'week_ending_2000-07-23', 'week_ending_2000-07-30', 'week_ending_2000-08-06', 'week_ending_2000-08-13', 'week_ending_2000-08-20', 'week_ending_2000-08-27', 'week_ending_2000-09-03', 'week_ending_2000-09-10', 'week_ending_2000-09-17', 'week_ending_2000-09-24', 'week_ending_2000-10-01', 'week_ending_2000-10-08', 'week_ending_2000-10-15', 'week_ending_2000-10-22', 'week_ending_2000-10-29', 'week_ending_2000-11-05', 'week_ending_2000-11-12', 'week_ending_2000-11-19', 'week_ending_2000-11-26', 'week_ending_2000-12-03', 'week_ending_2000-12-10', 'week_ending_2000-12-17', 'week_ending_2000-12-24', 'week_ending_2000-12-31', 'week_ending_2001-01-07', 'week_ending_2001-01-14', 'week_ending_2001-01-21', 'week_ending_2001-01-28', 'week_ending_2001-02-04', 'week_ending_2001-02-11', 'week_ending_2001-02-18', 'week_ending_2001-02-25', 'week_ending_2001-03-04', 'week_ending_2001-03-11', 'week_ending_2001-03-18', 'week_ending_2001-03-25', 'week_ending_2001-04-01', 'week_ending_2001-04-08', 'week_ending_2001-04-15', 'week_ending_2001-04-22', 'week_ending_2001-04-29', 'week_ending_2001-05-06', 'week_ending_2001-05-13', 'week_ending_2001-05-20', 'week_ending_2001-05-27', 'week_ending_2001-06-03', 'week_ending_2001-06-10', 'week_ending_2001-06-17', 'week_ending_2001-06-24', 'week_ending_2001-07-01', 'week_ending_2001-07-08', 'week_ending_2001-07-15', 'week_ending_2001-07-22', 'week_ending_2001-07-29', 'week_ending_2001-08-05', 'week_ending_2001-08-12', 'week_ending_2001-08-19', 'week_ending_2001-08-26', 'week_ending_2001-09-02', 'week_ending_2001-09-09', 'week_ending_2001-09-16', 'week_ending_2001-09-23', 'week_ending_2001-09-30', 'week_ending_2001-10-07', 'week_ending_2001-10-14', 'week_ending_2001-10-21', 'week_ending_2001-10-28', 'week_ending_2001-11-04', 'week_ending_2001-11-11', 'week_ending_2001-11-18', 'week_ending_2001-11-25', 'week_ending_2001-12-02', 'week_ending_2001-12-09', 'week_ending_2001-12-16', 'week_ending_2001-12-23', 'week_ending_2001-12-30', 'week_ending_2002-01-06', 'week_ending_2002-01-13', 'week_ending_2002-01-20', 'week_ending_2002-01-27', 'week_ending_2002-02-03', 'week_ending_2002-02-10', 'week_ending_2002-02-17', 'week_ending_2002-02-24', 'week_ending_2002-03-03', 'week_ending_2002-03-10', 'week_ending_2002-03-17', 'week_ending_2002-03-24', 'week_ending_2002-03-31', 'week_ending_2002-04-07', 'week_ending_2002-04-14', 'week_ending_2002-04-21', 'week_ending_2002-04-28', 'week_ending_2002-05-05', 'week_ending_2002-05-12', 'week_ending_2002-05-19', 'week_ending_2002-05-26', 'week_ending_2002-06-02', 'week_ending_2002-06-09', 'week_ending_2002-06-16', 'week_ending_2002-06-23', 'week_ending_2002-06-30', 'week_ending_2002-07-07', 'week_ending_2002-07-14', 'week_ending_2002-07-21', 'week_ending_2002-07-28', 'week_ending_2002-08-04', 'week_ending_2002-08-11', 'week_ending_2002-08-18', 'week_ending_2002-08-25', 'week_ending_2002-09-01', 'week_ending_2002-09-08', 'week_ending_2002-09-15', 'week_ending_2002-09-22', 'week_ending_2002-09-29', 'week_ending_2002-10-06', 'week_ending_2002-10-13', 'week_ending_2002-10-20', 'week_ending_2002-10-27', 'week_ending_2002-11-03', 'week_ending_2002-11-10', 'week_ending_2002-11-17', 'week_ending_2002-11-24', 'week_ending_2002-12-01', 'week_ending_2002-12-08', 'week_ending_2002-12-15', 'week_ending_2002-12-22', 'week_ending_2002-12-29', 'week_ending_2003-01-05', 'week_ending_2003-01-12', 'week_ending_2003-01-19', 'week_ending_2003-01-26', 'week_ending_2003-02-02', 'week_ending_2003-02-09', 'week_ending_2003-02-16', 'week_ending_2003-02-23', 'week_ending_2003-03-02', 'week_ending_2003-03-09', 'week_ending_2003-03-16', 'week_ending_2003-03-23', 'week_ending_2003-03-30', 'week_ending_2003-04-06', 'week_ending_2003-04-13', 'week_ending_2003-04-20', 'week_ending_2003-04-27', 'week_ending_2003-05-04', 'week_ending_2003-05-11', 'week_ending_2003-05-18', 'week_ending_2003-05-25', 'week_ending_2003-06-01', 'week_ending_2003-06-08', 'week_ending_2003-06-15', 'week_ending_2003-06-22', 'week_ending_2003-06-29', 'week_ending_2003-07-06', 'week_ending_2003-07-13', 'week_ending_2003-07-20', 'week_ending_2003-07-27', 'week_ending_2003-08-03', 'week_ending_2003-08-10', 'week_ending_2003-08-17', 'week_ending_2003-08-24', 'week_ending_2003-08-31', 'week_ending_2003-09-07', 'week_ending_2003-09-14', 'week_ending_2003-09-21', 'week_ending_2003-09-28', 'week_ending_2003-10-05', 'week_ending_2003-10-12', 'week_ending_2003-10-19', 'week_ending_2003-10-26', 'week_ending_2003-11-02', 'week_ending_2003-11-09', 'week_ending_2003-11-16', 'week_ending_2003-11-23', 'week_ending_2003-11-30', 'week_ending_2003-12-07', 'week_ending_2003-12-14', 'week_ending_2003-12-21', 'week_ending_2003-12-28', 'week_ending_2004-01-04', 'week_ending_2004-01-11', 'week_ending_2004-01-18', 'week_ending_2004-01-25', 'week_ending_2004-02-01', 'week_ending_2004-02-08', 'week_ending_2004-02-15', 'week_ending_2004-02-22', 'week_ending_2004-02-29', 'week_ending_2004-03-07', 'week_ending_2004-03-14', 'week_ending_2004-03-21', 'week_ending_2004-03-28', 'week_ending_2004-04-04', 'week_ending_2004-04-11', 'week_ending_2004-04-18', 'week_ending_2004-04-25', 'week_ending_2004-05-02', 'week_ending_2004-05-09', 'week_ending_2004-05-16', 'week_ending_2004-05-23', 'week_ending_2004-05-30', 'week_ending_2004-06-06', 'week_ending_2004-06-13', 'week_ending_2004-06-20', 'week_ending_2004-06-27', 'week_ending_2004-07-04', 'week_ending_2004-07-11', 'week_ending_2004-07-18', 'week_ending_2004-07-25', 'week_ending_2004-08-01', 'week_ending_2004-08-08', 'week_ending_2004-08-15', 'week_ending_2004-08-22', 'week_ending_2004-08-29', 'week_ending_2004-09-05', 'week_ending_2004-09-12', 'week_ending_2004-09-19', 'week_ending_2004-09-26', 'week_ending_2004-10-03', 'week_ending_2004-10-10', 'week_ending_2004-10-17', 'week_ending_2004-10-24', 'week_ending_2004-10-31', 'week_ending_2004-11-07', 'week_ending_2004-11-14', 'week_ending_2004-11-21', 'week_ending_2004-11-28', 'week_ending_2004-12-05', 'week_ending_2004-12-12', 'week_ending_2004-12-19', 'week_ending_2004-12-26', 'week_ending_2005-01-02', 'week_ending_2005-01-09', 'week_ending_2005-01-16', 'week_ending_2005-01-23', 'week_ending_2005-01-30', 'week_ending_2005-02-06', 'week_ending_2005-02-13', 'week_ending_2005-02-20', 'week_ending_2005-02-27', 'week_ending_2005-03-06', 'week_ending_2005-03-13', 'week_ending_2005-03-20', 'week_ending_2005-03-27', 'week_ending_2005-04-03', 'week_ending_2005-04-10', 'week_ending_2005-04-17', 'week_ending_2005-04-24', 'week_ending_2005-05-01', 'week_ending_2005-05-08', 'week_ending_2005-05-15', 'week_ending_2005-05-22', 'week_ending_2005-05-29', 'week_ending_2005-06-05', 'week_ending_2005-06-12', 'week_ending_2005-06-19', 'week_ending_2005-06-26', 'week_ending_2005-07-03', 'week_ending_2005-07-10', 'week_ending_2005-07-17', 'week_ending_2005-07-24', 'week_ending_2005-07-31', 'week_ending_2005-08-07', 'week_ending_2005-08-14', 'week_ending_2005-08-21', 'week_ending_2005-08-28', 'week_ending_2005-09-04', 'week_ending_2005-09-11', 'week_ending_2005-09-18', 'week_ending_2005-09-25', 'week_ending_2005-10-02', 'week_ending_2005-10-09', 'week_ending_2005-10-16', 'week_ending_2005-10-23', 'week_ending_2005-10-30', 'week_ending_2005-11-06', 'week_ending_2005-11-13', 'week_ending_2005-11-20', 'week_ending_2005-11-27', 'week_ending_2005-12-04', 'week_ending_2005-12-11', 'week_ending_2005-12-18', 'week_ending_2005-12-25', 'week_ending_2006-01-01', 'week_ending_2006-01-08', 'week_ending_2006-01-15', 'week_ending_2006-01-22', 'week_ending_2006-01-29', 'week_ending_2006-02-05', 'week_ending_2006-02-12', 'week_ending_2006-02-19', 'week_ending_2006-02-26', 'week_ending_2006-03-05', 'week_ending_2006-03-12', 'week_ending_2006-03-19', 'week_ending_2006-03-26', 'week_ending_2006-04-02', 'week_ending_2006-04-09', 'week_ending_2006-04-16', 'week_ending_2006-04-23', 'week_ending_2006-04-30', 'week_ending_2006-05-07', 'week_ending_2006-05-14', 'week_ending_2006-05-21', 'week_ending_2006-05-28', 'week_ending_2006-06-04', 'week_ending_2006-06-11', 'week_ending_2006-06-18', 'week_ending_2006-06-25', 'week_ending_2006-07-02', 'week_ending_2006-07-09', 'week_ending_2006-07-16', 'week_ending_2006-07-23', 'week_ending_2006-07-30', 'week_ending_2006-08-06', 'week_ending_2006-08-13', 'week_ending_2006-08-20', 'week_ending_2006-08-27', 'week_ending_2006-09-03', 'week_ending_2006-09-10', 'week_ending_2006-09-17', 'week_ending_2006-09-24', 'week_ending_2006-10-01', 'week_ending_2006-10-08', 'week_ending_2006-10-15', 'week_ending_2006-10-22', 'week_ending_2006-10-29', 'week_ending_2006-11-05', 'week_ending_2006-11-12', 'week_ending_2006-11-19', 'week_ending_2006-11-26', 'week_ending_2006-12-03', 'week_ending_2006-12-10', 'week_ending_2006-12-17', 'week_ending_2006-12-24', 'week_ending_2006-12-31', 'week_ending_2007-01-07', 'week_ending_2007-01-14', 'week_ending_2007-01-21', 'week_ending_2007-01-28', 'week_ending_2007-02-04', 'week_ending_2007-02-11', 'week_ending_2007-02-18', 'week_ending_2007-02-25', 'week_ending_2007-03-04', 'week_ending_2007-03-11', 'week_ending_2007-03-18', 'week_ending_2007-03-25', 'week_ending_2007-04-01', 'week_ending_2007-04-08', 'week_ending_2007-04-15', 'week_ending_2007-04-22', 'week_ending_2007-04-29', 'week_ending_2007-05-06', 'week_ending_2007-05-13', 'week_ending_2007-05-20', 'week_ending_2007-05-27', 'week_ending_2007-06-03', 'week_ending_2007-06-10', 'week_ending_2007-06-17', 'week_ending_2007-06-24', 'week_ending_2007-07-01', 'week_ending_2007-07-08', 'week_ending_2007-07-15', 'week_ending_2007-07-22', 'week_ending_2007-07-29', 'week_ending_2007-08-05', 'week_ending_2007-08-12', 'week_ending_2007-08-19', 'week_ending_2007-08-26', 'week_ending_2007-09-02', 'week_ending_2007-09-09', 'week_ending_2007-09-16', 'week_ending_2007-09-23', 'week_ending_2007-09-30', 'week_ending_2007-10-07', 'week_ending_2007-10-14', 'week_ending_2007-10-21', 'week_ending_2007-10-28', 'week_ending_2007-11-04', 'week_ending_2007-11-11', 'week_ending_2007-11-18', 'week_ending_2007-11-25', 'week_ending_2007-12-02', 'week_ending_2007-12-09', 'week_ending_2007-12-16', 'week_ending_2007-12-23', 'week_ending_2007-12-30', 'week_ending_2008-01-06', 'week_ending_2008-01-13', 'week_ending_2008-01-20', 'week_ending_2008-01-27', 'week_ending_2008-02-03', 'week_ending_2008-02-10', 'week_ending_2008-02-17', 'week_ending_2008-02-24', 'week_ending_2008-03-02', 'week_ending_2008-03-09', 'week_ending_2008-03-16', 'week_ending_2008-03-23', 'week_ending_2008-03-30', 'week_ending_2008-04-06', 'week_ending_2008-04-13', 'week_ending_2008-04-20', 'week_ending_2008-04-27', 'week_ending_2008-05-04', 'week_ending_2008-05-11', 'week_ending_2008-05-18', 'week_ending_2008-05-25', 'week_ending_2008-06-01', 'week_ending_2008-06-08', 'week_ending_2008-06-15', 'week_ending_2008-06-22', 'week_ending_2008-06-29', 'week_ending_2008-07-06', 'week_ending_2008-07-13', 'week_ending_2008-07-20', 'week_ending_2008-07-27', 'week_ending_2008-08-03', 'week_ending_2008-08-10', 'week_ending_2008-08-17', 'week_ending_2008-08-24', 'week_ending_2008-08-31', 'week_ending_2008-09-07', 'week_ending_2008-09-14', 'week_ending_2008-09-21', 'week_ending_2008-09-28', 'week_ending_2008-10-05', 'week_ending_2008-10-12', 'week_ending_2008-10-19', 'week_ending_2008-10-26', 'week_ending_2008-11-02', 'week_ending_2008-11-09', 'week_ending_2008-11-16', 'week_ending_2008-11-23', 'week_ending_2008-11-30', 'week_ending_2008-12-07', 'week_ending_2008-12-14', 'week_ending_2008-12-21', 'week_ending_2008-12-28', 'week_ending_2009-01-04', 'week_ending_2009-01-11', 'week_ending_2009-01-18', 'week_ending_2009-01-25', 'week_ending_2009-02-01', 'week_ending_2009-02-08', 'week_ending_2009-02-15', 'week_ending_2009-02-22', 'week_ending_2009-03-01', 'week_ending_2009-03-08', 'week_ending_2009-03-15', 'week_ending_2009-03-22', 'week_ending_2009-03-29', 'week_ending_2009-04-05', 'week_ending_2009-04-12', 'week_ending_2009-04-19', 'week_ending_2009-04-26', 'week_ending_2009-05-03', 'week_ending_2009-05-10', 'week_ending_2009-05-17', 'week_ending_2009-05-24', 'week_ending_2009-05-31', 'week_ending_2009-06-07', 'week_ending_2009-06-14', 'week_ending_2009-06-21', 'week_ending_2009-06-28', 'week_ending_2009-07-05', 'week_ending_2009-07-12', 'week_ending_2009-07-19', 'week_ending_2009-07-26', 'week_ending_2009-08-02', 'week_ending_2009-08-09', 'week_ending_2009-08-16', 'week_ending_2009-08-23', 'week_ending_2009-08-30', 'week_ending_2009-09-06', 'week_ending_2009-09-13', 'week_ending_2009-09-20', 'week_ending_2009-09-27', 'week_ending_2009-10-04', 'week_ending_2009-10-11', 'week_ending_2009-10-18', 'week_ending_2009-10-25', 'week_ending_2009-11-01', 'week_ending_2009-11-08', 'week_ending_2009-11-15', 'week_ending_2009-11-22', 'week_ending_2009-11-29', 'week_ending_2009-12-06', 'week_ending_2009-12-13', 'week_ending_2009-12-20', 'week_ending_2009-12-27', 'week_ending_2010-01-03', 'week_ending_2010-01-10', 'week_ending_2010-01-17', 'week_ending_2010-01-24', 'week_ending_2010-01-31', 'week_ending_2010-02-07', 'week_ending_2010-02-14', 'week_ending_2010-02-21', 'week_ending_2010-02-28', 'week_ending_2010-03-07', 'week_ending_2010-03-14', 'week_ending_2010-03-21', 'week_ending_2010-03-28', 'week_ending_2010-04-04', 'week_ending_2010-04-11', 'week_ending_2010-04-18', 'week_ending_2010-04-25', 'week_ending_2010-05-02', 'week_ending_2010-05-09', 'week_ending_2010-05-

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv("data.csv")

X = df.iloc[:, :-1]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
if 'column_name' not in X_train.columns:
    print("Column not found. Available columns:", list(X_train.columns))

Column not found. Available columns: ['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se', 'fractal_dimension_se', 'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst', 'smoothness_worst', 'compactness_worst', 'concavity_worst', 'concave points_worst', 'symmetry_worst', 'fractal_dimension_worst']

In [15]:
y_train = y_train.fillna(y_train.mean())

In [20]:
print(df.isnull().sum())   # check missing values
print(df.shape)            # check dataset size
print(df.columns)         # confirm column names

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64
(569, 33)
Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

In [22]:
y_train.isna().sum()

np.int64(455)

In [24]:
from sklearn.utils.validation import check_is_fitted

check_is_fitted(rf_model)