In [1]:
import pandas as pd
import numpy as np

# NLP
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

# Sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Visualization
import matplotlib.pyplot as plt

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
df = pd.read_csv("hospital_ratings.csv")

df.head()

   Unnamed: 0 mortality_rate  quality_rating
0           0        average               1
1           1  below_average               4
2           2  above_average               1
3           3        average               4
4           4        average               4

In [4]:
print([col for col in df.columns if "review" in col.lower() or "text" in col.lower()])

[]

In [7]:
print(df["quality_rating"].head())
print(df["mortality_rate"].head())

0    1
1    4
2    1
3    4
4    4
Name: quality_rating, dtype: int64
0          average
1    below_average
2    above_average
3          average
4          average
Name: mortality_rate, dtype: str

In [10]:
df_encoded = pd.get_dummies(df)
X = StandardScaler().fit_transform(df_encoded)

In [11]:
df.head()

   Unnamed: 0 mortality_rate  quality_rating
0           0        average               1
1           1  below_average               4
2           2  above_average               1
3           3        average               4
4           4        average               4

In [12]:
df.dtypes

Unnamed: 0        int64
mortality_rate      str
quality_rating    int64
dtype: object

In [17]:
docs = [
    "dog bites man",
    "man bites dog",
    "dog eats food",
    "cat eats food"
]

In [20]:
print(type(X))

<class 'numpy.ndarray'>

In [22]:
df.head()
df.columns

Index(['Unnamed: 0', 'mortality_rate', 'quality_rating'], dtype='str')

In [23]:
if "rating" in df.columns:
    print(df.groupby("cluster")["rating"].mean())