In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [2]:
# Load CSV file
df = pd.read_csv("missions.csv")

# View data
print(df.head())
print(df.info())

   Mission  ...                                        Description
0        0  ...                               Escape the hospital.
1        1  ...  Rescue your old partner, Kazuhira Miller. He h...
2        2  ...                                                NaN
3        3  ...                                                NaN
4        4  ...                                                NaN

[5 rows x 6 columns]
<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Mission        51 non-null     int64
 1   Mission Title  51 non-null     str
 2   Location       46 non-null     str
 3   GMP            38 non-null     float64
 4   Tasks          38 non-null     float64
 5   Description    2 non-null      str
dtypes: float64(2), int64(1), str(3)
memory usage: 4.8 KB
None

In [4]:
from sklearn.preprocessing import LabelEncoder

df = df.dropna()

label_encoders = {}

categorical_cols = df.select_dtypes(include=["object"]).columns

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

print(df.head())

   Mission  Mission Title  Location      GMP  Tasks  Description
0        0              0         0      0.0    2.0            0
1        1              1         1  80000.0    6.0            1

In [6]:
for col in df.columns:
    print(repr(col))

'Mission'
'Mission Title'
'Location'
'GMP'
'Tasks'
'Description'

In [10]:
print(df.columns)

Index(['Mission', 'Mission Title', 'Location', 'GMP', 'Tasks', 'Description'], dtype='str')

In [16]:
print(df.columns)

Index(['Mission', 'Mission Title', 'Location', 'GMP', 'Tasks', 'Description'], dtype='str')

In [21]:
df.head()

   Mission  ...                                        Description
0        0  ...                               Escape the hospital.
1        1  ...  Rescue your old partner, Kazuhira Miller. He h...
2        2  ...                                                NaN
3        3  ...                                                NaN
4        4  ...                                                NaN

[5 rows x 6 columns]

In [22]:
print(df.columns)
df.head()

Index(['Mission', 'Mission Title', 'Location', 'GMP', 'Tasks', 'Description'], dtype='str')

   Mission  ...                                        Description
0        0  ...                               Escape the hospital.
1        1  ...  Rescue your old partner, Kazuhira Miller. He h...
2        2  ...                                                NaN
3        3  ...                                                NaN
4        4  ...                                                NaN

[5 rows x 6 columns]

In [28]:
df.head()

   Mission  ...                                        Description
0        0  ...                               Escape the hospital.
1        1  ...  Rescue your old partner, Kazuhira Miller. He h...
2        2  ...                                                NaN
3        3  ...                                                NaN
4        4  ...                                                NaN

[5 rows x 6 columns]

In [32]:
dir()

['ExtraTreesClassifier',
 'In',
 'LabelEncoder',
 'Out',
 'RandomForestClassifier',
 '_',
 '_21',
 '_22',
 '_28',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__session__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'accuracy_score',
 'categorical_cols',
 'classification_report',
 'col',
 'confusion_matrix',
 'df',
 'et_model',
 'exit',
 'get_ipython',
 'label_encoders',
 'le',
 'np',
 'open',
 'pd',
 'plt',
 'quit',
 'rf_model',
 'target_col',
 'train_test_split']