In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df = pd.read_csv("unemployment-macro.csv")

df.head()

         date  total_unemployed  ...  leavers  losers
0  2010-11-01              16.9  ...      5.7    63.0
1  2010-12-01              16.6  ...      6.4    61.2
2  2011-01-01              16.2  ...      6.5    60.1
3  2011-02-01              16.0  ...      6.4    60.2
4  2011-03-01              15.9  ...      6.4    60.3

[5 rows x 7 columns]

In [3]:
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   date                            74 non-null     str
 1   total_unemployed                74 non-null     float64
 2   more_than_15_weeks              74 non-null     int64
 3   not_in_labor_searched_for_work  74 non-null     int64
 4   multi_jobs                      74 non-null     int64
 5   leavers                         74 non-null     float64
 6   losers                          74 non-null     float64
dtypes: float64(3), int64(3), str(1)
memory usage: 4.9 KB
None
       total_unemployed  more_than_15_weeks  ...    leavers     losers
count         74.000000           74.000000  ...  74.000000  74.000000
mean          12.859459         5524.635135  ...   8.656757  52.698649
std            2.358367         1862.516898  ...   1.524061   4.136423
min            9.200000         2929.000000  ...   5.700000  47.400000
25%           10.550000         3560.000000  ...   7.600000  48.975000
50%           13.100000         5653.500000  ...   8.400000  52.300000
75%           14.775000         7086.250000  ...   9.700000  55.275000
max           16.900000         8696.000000  ...  12.500000  63.000000

[8 rows x 6 columns]
date                              0
total_unemployed                  0
more_than_15_weeks                0
not_in_labor_searched_for_work    0
multi_jobs                        0
leavers                           0
losers                            0
dtype: int64

In [4]:
# Fill missing values (if any)
df = df.fillna(df.mean(numeric_only=True))

In [6]:
df = df.rename(columns={"Unemployment Rate": "Unemployment_Rate"})

In [10]:
df.columns
df.head()

         date  total_unemployed  ...  leavers  losers
0  2010-11-01              16.9  ...      5.7    63.0
1  2010-12-01              16.6  ...      6.4    61.2
2  2011-01-01              16.2  ...      6.5    60.1
3  2011-02-01              16.0  ...      6.4    60.2
4  2011-03-01              15.9  ...      6.4    60.3

[5 rows x 7 columns]

In [13]:
print(locals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'DecisionTreeRegressor', 'RandomForestRegressor', 'mean_squared_error', 'r2_score', '_i2', 'df', '_2', '_i3', '_i4', '_i5', 'target_column', '_i6', '_i7', '_i8', '_i9', '_i10', '_10', '_i11', 'dt_model', '_i12', '_i13'])

In [16]:
(df.columns)

Index(['date', 'total_unemployed', 'more_than_15_weeks',
       'not_in_labor_searched_for_work', 'multi_jobs', 'leavers', 'losers'],
      dtype='str')

In [20]:
X = df.values